task: class
epoch: 50
batchsize: 64
model: efficientnet-b3
optimizer: adam
loss: crossentropy
lr: 1e-3
image_size: 512
n_class: 5
lr_scheduler:
  name: CosineAnnealing
  option: 
    T_max: 10
    eta_min: 0.00001

