task: reg
epoch: 50
batchsize: 128
model: efficientnet-b3
optimizer: adam
loss: mse
lr: 1e-3
image_size: 320
n_class: 1
lr_scheduler:
  name: CosineAnnealing
  option: 
    T_max: 10
    eta_min: 0.00001

